### ISSUE TITLE
Coin Earnings

### ISSUE THREAD

**Issue by SirArkimedes** [CTC-CompTech/delivery#10]
Level 1: 10
Level 2: 25
Level 3: 50
Level 4: 100
Level 5: 150

**Comment by TheGoldenPerspective** [comment]
Lvl 1- 1-5 blocks
Lvl 2- 5-15 blocks
Lvl 3- 15-25 blocks
Lvl 4- 25-40 blocks
Lvl 5- 40-  blocks
