### ISSUE TITLE
Achievement ideas

### ISSUE THREAD

**Issue by SirArkimedes** [CTC-CompTech/delivery#11]
We are already have a few achievements being tracked, I was just like to get some ideas of achievements down in writing.

Current tracked stats:
- Total coins
- Current coins
- Collision count
- Games ran

**Comment by TheGoldenPerspective** [comment]
- Have all cars unlocked 
- Use all abilities at least once

**Comment by Cast324** [comment]
- Unlocking cars
- Using a car so many times
- Playing multi-player (If added)
