### ISSUE TITLE
Color schemes

### ISSUE THREAD

**Issue by TheGoldenPerspective** [CTC-CompTech/delivery#12]
Currently we have no set color scheme(s)

It would be nice to have a set color scheme for everything or have set color schemes for different things. 

Thanks

**Comment by SirArkimedes** [comment]
![delvierycoposterv2](https://cloud.githubusercontent.com/assets/3119506/6072061/84c500ce-ad62-11e4-8cb1-7b657b9059e1.png)

**Comment by mrsriley358** [comment]
At the scheduling thing.
![img_2880](https://cloud.githubusercontent.com/assets/3119506/6072120/44b55ef6-ad63-11e4-9ce5-754d4cccfa24.JPG)

Renee Riley
IT Instructor
1100 E. Airport Dr.
Carthage, MO 64836
(417) 359-7026

Sent from my iPhone

On Feb 5, 2015, at 6:12 PM, Andrew Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

Renee Riley
IT Instructor
1100 E. Airport Dr.
Carthage, MO 64836
(417) 359-7026

Sent from my iPhone
