### ISSUE TITLE
can't run on xcode 6.1

### ISSUE THREAD

**Issue by arden** [CTC-CompTech/delivery#16]
when i'm run it on xcode 6.1 that：

error: /Users/arden/data/source/ios/游戏/delivery/Source/Resources/Published-iOS: No such file or directory

**Comment by SirArkimedes** [comment]
That looks like you haven't used Spritebuilder to publish the project. If you need Spritebuilder: https://itunes.apple.com/us/app/spritebuilder/id784912885?mt=12
