### ISSUE TITLE
Increasingly Harder difficulty

### ISSUE THREAD

**Issue by SirArkimedes** [CTC-CompTech/delivery#3]
Difficulty should change for the longer the user goes, The truck may get faster, or the obstacles get closer together.

**Comment by SirArkimedes** [comment]
This is assuming the game will be infinitely long.

**Comment by TheGoldenPerspective** [comment]
If the game is infinitely long it should start rather slow and then slowly increase in speed.  Also when the game is not infinitely long the speed should also slowly increase in speed as the levels continue on.  Also we could implement maybe starting with only two obstacles at first and slowly increase until we achieve four obstacles and only one open lane.

**Comment by SirArkimedes** [comment]
Completed.
