### ISSUE TITLE
Company Name?!

### ISSUE THREAD

**Issue by TheGoldenPerspective** [CTC-CompTech/delivery#4]
Currently we are in need of a company name for our delivery service. This name would go on the top the truck and would probably go on coin rewards and any other rewards.

Along with this a company logo would be better for the coin rewards, but a name is needed first.

**Comment by SirArkimedes** [comment]
My ideas:
- USSS
- US^3
- United States Shipping Service

**Comment by TheGoldenPerspective** [comment]
Works for me, I am going to  post a picture to the drive as an idea for the logo see what you think.

**Comment by mrsriley358** [comment]
Umazon

iPS (intl parcel shipping)

Renee Riley
IT Instructor
1100 E. Airport Dr.
Carthage, MO 64836
(417) 359-7026

**Comment by Cast324** [comment]
All of these work for me.

**Comment by SirArkimedes** [comment]
![possible logo](https://cloud.githubusercontent.com/assets/3119506/5638919/b3b4c488-95d3-11e4-8b73-3ef44b2eab77.png)
- From Jared

**Comment by SirArkimedes** [comment]
USSS or US^3 is what we're going with.
